### ISSUE TITLE
Inzetbaarheidsuren random op 0

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#10]
Bij medewerker 700576 van de Pius X stond de inzetbaarheid op 0 bij het openen van het contract. Dit gebeurt random wel eens vaker.
Bij het aanpassen van de opslagfactor naar 0, worden de inzetbaarheidsuren weer correct ingevuld.

Het lijkt er op dat de WTF op 0 gezet wordt.

Het is mij onduidelijk hoe deze bug ontstaat

**Comment by MartijnLans** [comment]
De bug lijkt steeds vaker voor te komen. Mogelijk (maar niet zeker) heeft dit te maken met wijzigingen in de basisgegevens na het aanmaken van een overeenkomst.

**Comment by stegeman** [comment]
Gaat het hier om een het 'Totaal' in de kolom 'Uw inzetbaarheid' op het tabblad inzetbaarheid? 

Ik krijg het niet gereproduceerd. Als jij me d.m.v. een screenshot kan laten zien wat er precies gebeurd krijg ik misschien wat meer aanknopingspunten. Of als je een nieuw voorbeeld hebt waar dit op dit moment nog speelt dan hoor ik dat graag.

**Comment by MartijnLans** [comment]
Ik denk dat ik er per ongeluk achter ben hoe dit probleem ontstaat. Hierbij een screenshot van het probleem:
https://ibb.co/b6hn1o

Om het probleem te laten voorkomen heb ik tabblad WTF ingevuld, en ben ik direct doorgegaan naar de planning, zonder inzetbaarheid te openen. De planning heb ik opgeslagen, waardoor de inzetbaarheid ook opgeslagen is met alle uren op 0.
Een fix hiervoor zou denk ik zijn om de planning te blokkeren, totdat de inzetbaarheid is opgeslagen. (net zoals het nu gaat als de WTF nog niet is ingevuld)

Mochten er nog meer manieren zijn om deze bug te reproduceren dan zal ik dat melden, maar dit is de enige manier die ik kan gevonden heb.

**Comment by stegeman** [comment]
Het is mij inderdaad ook gelukt om het op deze manier te reproduceren. De planning tab blijft nu disabled tot de inzetbaarheid is ingevuld. Deze functionaliteit staat op de acceptatie omgeving. Als jij het wilt testen dan kan het daarna hopelijk naar productie.

**Comment by MartijnLans** [comment]
Getest, werkt volgens mij helemaal prima en kan dus naar live..
