### ISSUE TITLE
uren bij het 2 wekelijks rooster

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#12]
Als de dagen worden uitgevinkt en er wordt opgeslagen, en daarna de uren weer aangevinkt worden, dan worden de uren van het rooster niet meer ingevuld. (2 wekelijks rooster)

Verder als er na het uitvinken van een dag + opslaan nogmaals op wordt geslagen, wordt er gevraagd om bij uitgevinkte dagen alsnog de uren in te vullen. (ook bij normaal rooster)

**Comment by stegeman** [comment]
Bij het fixen van issue #4 heb ik deze ook gelijk opgelost. Wanneer het aantal uren dat aan een disabled dag zitten op 0 staat worden de gegevens van de betreffende dag uit het geselecteerde rooster ingevuld wanneer de dag weer enabled wordt. Een hele zin, maar ik hoop dat je het begrijpt :).

**Comment by MartijnLans** [comment]
Eventuele issues die hier mee te maken hebben zal ik vervolgen bij https://github.com/MartijnLans/PM-TOP/issues/4.
De uren terugzetten en op 0 zetten lijkt goed te werken.
