### ISSUE TITLE
mail layout

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#13]
< p>Beste Martijn Lans,< /p> < p>Martijn heeft op PM-TOP een nieuw overeenkomst voor je opgesteld op 25-06-2018. Bekijk het overeenkomst en controleer je gegevens. Daarna kun je op de laatste pagina tekenen voor akkoord.</p><p>Met vriendelijke groet,< /p>Het Support Team

De layout < p>tjes moeten niet zichtbaar zijn bij een mail dat de overeenkomst opgesteld is.

**Comment by MartijnLans** [comment]
Behalve de layout (Ptjes) ben ik er vandaag ook op gewezen dat er "het overeenkomst" staat. Dit is nog een restant van het contract, en moet worden "de overeenkomst"
+ "een nieuw overeenkomst" moet zijn "een nieuw**e** overeenkomst"

**Comment by stegeman** [comment]
Is aangepast

**Comment by MartijnLans** [comment]
![nieuwe bitmapafbeelding](https://user-images.githubusercontent.com/39770147/49085778-1c8cd880-f253-11e8-9e86-39ee815a6f98.jpg)

Issue met de < P> lijkt weer terug te zijn. Zou je hier naar willen kijken?

**Comment by stegeman** [comment]
Het probleem is als het goed is opgelost. Het content type van de mail stond op plain/text en niet op text/html.
Ik kan het niet testen, want mijn mail client geeft alles goed weer.

**Comment by MartijnLans** [comment]
Hoi @stegeman ,

Ik krijg op het moment helemaal geen mail meer binnen van PM-TOP.

**Comment by stegeman** [comment]
Hm, dat is raar. Heb het net meerdere malen getest en ik krijg alles binnen. Het viel me wel op dat het soms even duurt voordat je het binnen krijgt.

Op welk email adres krijg je het niet binnen? Mocht je nog een email hebben, wil je het daar dan eens op proberen?

**Comment by MartijnLans** [comment]
@stegeman het heeft +/- 29 uur geduurd voordat de mails binnenkwamen, maar ze zijn uiteindelijk toch binnengekomen.
Daarnaast geen problemen meer met de layout

**Comment by stegeman** [comment]
@MartijnLans dit lijkt me een hosting issue. Als ik jou was zou ik dat even opnemen met de hosting partij

**Comment by MartijnLans** [comment]
@stegeman ga ik doen!
