### ISSUE TITLE
Opslagfactor aanpassen werkt niet

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#16]
Als er een model geselecteerd is op tab 1 van de overeenkomst, en in tab 2 wordt een andere dan de standaard opslagfactor ingevuld in het blauwe veld, dan rekent PM-TOP de uren goed uit. Echter wordt dit bij opslaan weer overschreven door de oude uren, terwijl de opslagfactor wel op het aangepaste percentage blijft staan.

**Comment by stegeman** [comment]
Een fix hiervoor staat op acceptatie

**Comment by MartijnLans** [comment]
Fix werkt goed en kan naar live.

**Comment by MartijnLans** [comment]
Een bug die hier mee te maken heeft is dat de overige taken niet meer worden, als de opslagfactor kleiner wordt (en vice versa).
Dit moet ik nog even overleggen, dus hoeft nog niet gefixed te worden zolang het wontfix label er op staat.

**Comment by MartijnLans** [comment]
De uren die vrij komen of verminderd worden door de lagere of hogere opslagfactor moeten gecorrigeerd worden op de overige taken.

**Comment by stegeman** [comment]
Norm wordt nu ook meeberekend. Dit staat nu alleen nog op acceptatie

Even als extra check; Als een opslagfactor wordt gewijzigd moet subtotaal niet veranderen van waarde?

**Comment by MartijnLans** [comment]
Subtotaal moet inderdaad niet veranderen.
Het lijkt op de testomgeving goed te werken en kan dus naar live.
