### ISSUE TITLE
Overeenkomst herberekenen 

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#17]
Als voorbeeld bij de Laurentius SBO:

personeelsnummer 4258 | overeenkomst 00019772
Als de knop herberekenen wordt gebruikt, dit nodig is om bug https://github.com/MartijnLans/PM-TOP/issues/16 te omzeilen , krijg je een error:

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

Dit gebeurt bij enkele mensen.

**Comment by stegeman** [comment]
Waar zit de herberekenen knop? Deze kan ik niet vinden. Bedoel je soms de reset knop op het planning tabblad?

**Comment by MartijnLans** [comment]
Als je bij inzetbaarheid (buiten overeenkomst) zit, kan je met de opties knop (rechts van de overeenkomst) kiezen voor verwijder etc. etc. hier staat ook herbereken tussen,.

**Comment by stegeman** [comment]
Het lijkt er op dat dit probleem inmiddels niet meer bestaat. Kan jij dit nog eens checken?

**Comment by MartijnLans** [comment]
Hoi, ik kan dit niet meer reproduceren. Het gebeurde maar bij een beperkt aantal medewerkers, maar ik ben bang dat ik ingevulde contracten per ongeluk bewerk als ik het bij deze medewerker test.

Voor nu sluit ik de issue.
