### ISSUE TITLE
Versturen als PDF - tekst verdwijnt

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#18]
Als er bij de bevestiging tekst wordt getypt, en dan zonder eerst op te slaan de PDF verstuurd wordt, dan is de tekst verdwenen.
Misschien is het een optie om te knop "Verstuur" automatisch eerst te laten opslaan, zodat getypte tekst niet zomaar verdwijnt.

**Comment by stegeman** [comment]
Een fix hiervoor staat op acceptatie. Check even of het werkt, dan kan het naar productie.

**Comment by MartijnLans** [comment]
Werkt op de testomgeving.

**Comment by MartijnLans** [comment]
Deze issue is nog steeds aanwezig op de live versie.

**Comment by stegeman** [comment]
Deze fix staat nu ook op productie

**Comment by MartijnLans** [comment]
Tekst wordt goed opgeslagen.
