### ISSUE TITLE
Wijziging woordkeuze (overeenkomst ipv contract)

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#2]
In PM-Top wordt het woord “contract” gebruikt.
Het woord contract kan vervangen worden door “overeenkomst” Dit moet gewijzigd worden op alle plaatsen waar dit voorkomt. Enkele voorbeelden:
-	Plan van Inzet (kopje Inzetbaarheid).  Het kopje Contract.
-	PDF bestandsnaam bij het versturen vanuit de overeenkomst (verstuur als PDF) + de bijbehorende mail tekst & onderwerp
-	In het PDF bestand “Contract 2017/2018”
-	Mail, via de knop “verstuur”. Zowel onderwerp als tekst

**Comment by stegeman** [comment]
Ik heb de codebase doorzocht en alle weergaven van het woord contract vervangen voor overeenkomst.

**Comment by MartijnLans** [comment]
Het lijkt er op dat alles opgelost is, behalve de bestandsnaam van het verstuurde PDFje. Dit is nog "contract".

**Comment by stegeman** [comment]
Die was ik vergeten. Heb ik nu ook aangepast.
