### ISSUE TITLE
Opslaan tabblad bevestiging #500 error

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#20]
Als de knop opslaan gebruikt wordt op het laatste tabblad (Bevestiging) dan krijg je een #500 internal server error.
Als de knop "verstuur" gebruikt wordt, werkt dit wel gewoon (en wordt er opgeslagen).

**Comment by stegeman** [comment]
Een eerste bug in het systeem is opgelost. Echter is het probleem daar nog niet mee opgelost. Hier kijk ik morgen verder naar.

**Comment by stegeman** [comment]
De nieuwe versie staat nu op de acceptatie omgeving. Kan getest worden
