### ISSUE TITLE
#403 error

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#21]
Als ik vanuit de school naar inzetbaarheid ga (dus niet in de overeenkomst), en daar klik op de knop verstuur om een mail te sturen dat de overeenkomst klaar staat, dan krijg ik een 403 forbidden error.

**Comment by stegeman** [comment]
Fix staat op acceptatie. Kan getest worden.

**Comment by MartijnLans** [comment]
Fixed
