### ISSUE TITLE
Inlezen personeel geboortedatum

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#24]
Bij het inlezen van het personeel komt de datum op 21-01-1900 te staan.
Zie bijlage voor het gebruikte inleesbestand.
[users.xlsx](https://github.com/MartijnLans/PM-TOP/files/2331375/users.xlsx)

**Comment by stegeman** [comment]
Het uploaden van de geboortedatums is nu gefixt. Staat op zowel productie als test

**Comment by MartijnLans** [comment]
Inlees bestandje is nu correct ingelezen.

**Comment by MartijnLans** [comment]
Bug weer aanwezig

**Comment by stegeman** [comment]
Heb je een voorbeeld van een file waar het bij fout gaat? Dan kan ik op basis daarvan uitzoeken wat er fout gaat.

**Comment by MartijnLans** [comment]
Het zelfde bestand als in de main post kan hiervoor gebruikt worden. Bij het updaten van de medewerkers wordt dan de geboortedatum verkeerd aangepast.

**Comment by stegeman** [comment]
Ik heb hier een extra fix voor geschreven. Even aankijken of het op die manier wel goed werkt.

Fix staat op zowel acc als prod.

**Comment by MartijnLans** [comment]
[users (13).xlsx](https://github.com/MartijnLans/PM-TOP/files/3410872/users.13.xlsx)
Zie bestandje. Als de datum in Excel als datum staat (wat op een of andere manier standaard is als ik nu op enter druk na een datum in te vullen), dan leest de datum niet in.
Regel 1 staat als "Standaard" en regel 2 staat als "Datum".

**Comment by stegeman** [comment]
Volgende poging. Op productie lukt het me nu om de excel in te lezen en de geboortedatum wordt nu goed geïmporteerd. Het zou goed kunnen dat er nog meer vormen van datums in een excel kunnen zitten, maar deze twee vormen worden nu goed afgehandeld.

**Comment by MartijnLans** [comment]
Werkt weer.
Echter een nieuwe issue met 500 errors, zie https://github.com/MartijnLans/PM-TOP/issues/33#issue-475507564
