### ISSUE TITLE
Planbord (Excel download)

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#26]
Als de overeenkomsten van de medewerkers ingevuld zijn, dan komen de uren in het planbord te staan.
Bij het downloaden van het planbord valt echter de laatste regel weg, en bij mijn test PM-TOP op de live omgeving vielen zelfs de uren van de laatste 2 rijen weg.

![nieuwe bitmapafbeelding](https://user-images.githubusercontent.com/39770147/44789599-458ec600-ab9d-11e8-82a9-a2f31dd19b3f.jpg)
![nieuwe bitmapafbeelding - kopie 2](https://user-images.githubusercontent.com/39770147/44789600-458ec600-ab9d-11e8-8f40-4f080a4de212.jpg)

**Comment by stegeman** [comment]
Een fix voor deze bug staat op prod. Zou jij willen checken of het nu helemaal klopt?

Is de acc omgeving trouwens nog down? Het lijkt er op dat ik er niet bij kan.

**Comment by MartijnLans** [comment]
Hoi René,

Na de laatste fix gaat er iets mis met de personeelsnummers. In de personeelslijsten zijn nu alle personeelsnummers anders dan 1 aangepast van 124 naar -124. Daarnaast als ik nu een bestaand bestand inlees, dan wordt 124 aangepast naar -123.

Daarnaast wordt er bij een leeg veld bij Categorie van een inlees bestand automatisch DIR en OP ingelezen. Dit is uiteraard niet de bedoeling.

Als het mogelijk is om de versie terug te zetten naar de versie van gisteren, dan graag. Volgende week woensdag heb ik namelijk een afspraak voor PM-TOP. Graag in ieder geval t/m woensdag even geen wijzigingen op live maken. De andere omgeving doet het inderdaad niet, maar de personen die daar bij kunnen zijn op vakantie.

**Comment by stegeman** [comment]
Wat je hier bedoeld is een error in de import toch? Op het eerste gezicht lijkt dit me niet gerelateerd aan bovenstaande fix. Ik zal vanavond even kijken hoe dit op te lossen.

**Comment by MartijnLans** [comment]
Hoi René, bovenstaande is ontstaan sinds de laatste fix.
Echter staat bij iedere stichting nu het personeelsnummer in de min (-123 ipv 123). Dit zonder hier extra voor te importeren.

De overige issues zijn na importeren.
Als het mogelijk is om dit vandaag op te lossen dan graag, mocht dit niet lukken dan graag terugzetten naar de versie van gisteren.

**Comment by stegeman** [comment]
Het probleem met de negatieve personeelnummers is opgelost.

Vanavond zal ik kijken naar het DIR / OP probleem bij de import. Hier maak ik even een apart issue voor aan.
