### ISSUE TITLE
403 Forbidden wachtwoord reset

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#27]
Als ik al directeur het wachtwoord van een andere directeur wil resetten dan krijg ik een 403 Forbidden error.
Het klopt volgens mij dat een directeur niet van een andere directeur het wachtwoord kan resetten, maar dit zou geen server error moeten opleveren.

**Comment by stegeman** [comment]
Er wordt nu een foutmelding weergegeven dat een directeur het wachtwoord van een andere directeur niet mag wijzigen.

Dit staat op acceptatie en kan getest worden

**Comment by MartijnLans** [comment]
Werkt goed, bedankt!

**Comment by MartijnLans** [comment]
Op het moment wordt er op de live versie nog geen foutmelding weergegeven. Zou je dit willen updaten?
