### ISSUE TITLE
mail overeenkomst staat klaar

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#29]
Zou je in de mail de volgende link willen opnemen?
Sommige medewerkers weten niet waar ze moeten inloggen.

https://login.pm-top.nl/login

**Comment by stegeman** [comment]
Tekstuele wijziging staat op zowel productie als acceptatie

**Comment by MartijnLans** [comment]
Uw werkgever heeft op PM-TOP een **nieuw** overeenkomst voor je opgesteld op 25-02-2019. Bekijk **het** overeenkomst via deze link en controleer je gegevens. Daarna kun je op de laatste pagina tekenen voor akkoord.

Zou je alleen nog "nieuw" willen vervangen door "nieuwe" en "het" door "de"?
Verder prima!

**Comment by MartijnLans** [comment]
Link staat niet meer in de mail.

**Comment by stegeman** [comment]
Heb hem weer toegevoegd. De zelfde spellingsfout stond er ook nog in, heb ik ook weer aangepast.

**Comment by MartijnLans** [comment]
Dat is vreemd, ik krijg namelijk de versie zonder spelfout.
Er staat nu weer "nieuw" ipv "nieuwe". Zou je dit nog willen aanpassen?

**Comment by stegeman** [comment]
Heb ik ook aangepast.

**Comment by stegeman** [comment]
Heb ik weer aangepast. Zou nu wel goed moeten gaan.
