### ISSUE TITLE
Aanmaken van gebruiker verstuurd geen mail

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#31]
Volgens mij zou bij het aanmaken van een gebruiker zou er een mail met inloggegevens verstuurd moeten worden naar de betreffende medewerker.
Op het moment moet ik een wachtwoord reset doen direct na het aanmaken van een gebruiker om de medewerker van inloggegevens te voorzien.

Klopt het dat dit voorheen wel gebeurde? Zo niet, dan graag alsnog inbouwen.

**Comment by stegeman** [comment]
De fix hiervoor staat op acc

**Comment by MartijnLans** [comment]
Fix werkt prima en kan naar de live versie.
