### ISSUE TITLE
Schooljaar 2019-2020

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#32]
Het schooljaar bij inloggen staat op 2018-2019. Graag wijzigen naar 2019-2020 zodat de klanten direct in het juiste jaar werken.

**Comment by stegeman** [comment]
Ik heb een change gedaan waardoor vanaf 1 juli het jaar verspringt naar het volgende jaar.

Bij het live zetten is de site een kleine 10 minuten down geweest, mocht je hier vragen over krijgen.

**Comment by MartijnLans** [comment]
Opgelost.
