### ISSUE TITLE
Standaard DIR / OP voor lege categorie

### ISSUE THREAD

**Issue by stegeman** [MartijnLans/PM-TOP#34]
bij een leeg veld bij Categorie van een inlees bestand wordt automatisch DIR en OP ingelezen. Dit is uiteraard niet de bedoeling.

**Comment by stegeman** [comment]
Deze bug is gefixt. Wanneer Categorie niet is ingevuld in de sheet krijg de gebruiker geen rollen toegekend.

**Comment by MartijnLans** [comment]
Top, bedankt!
