### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#35]
Bij het laatste tabblad "bevestiging" kan een mailadres worden ingevuld om als PDF te verzenden.
Als er op de knop "verstuur" wordt gedrukt, dan krijg je een 500 Internal Server Error.

Zou je willen kijken of je hier een oplossing voor kan vinden?

**Comment by MartijnLans** [comment]
Even voor mezelf:
Doorgeven aan istvan OBO als het weer werkt.

**Comment by stegeman** [comment]
Ik vrees dat het probleem echt te maken heeft met de hosting. Heb je voor mij de gegevens waarme ik kan contacten met de systeembeheerder van het hostingplatform? Dan kan ik het even direct met hem opnemen.

Aan de code ligt het iig niet, want het werkt op mijn omgeving helemaal prima.

**Comment by MartijnLans** [comment]
Beste Rene,

Martijn is op dit moment op vakantie, ik neem zijn taken van PM-TOP over.

De hosting omgeving van PM-TOP staat in Capelle het telefoonnummer hiervan is 010-4517676, je kunt dan vragen naar Hans van Zijl.

Mocht je meer weten zou je mij dan willen mailen


Mijn mailadres is pvpraag@onderwijssupport.nl

Ik hoor graag zo spoedig mogelijk van je, de vragen over het versturen van de contracten stromen nu een beetje binnen.


Groet,

Patrick van Praag


Met vriendelijke groet,
Martijn Lans

[logo-pmos]<http://www.onderwijssupport.nl/>
[http://www.onderwijssupport.nl/images/handtekening/ico-tel.png]
+31 (0)15 251 14 50
[http://www.onderwijssupport.nl/images/handtekening/ico-home.png]
Burgemeestersrand 59

2625 NV Delft
De informatie verzonden met dit e-mailbericht is uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking en/of verstrekking van deze informatie aan derden is niet toegestaan. Pro Management Onderwijs Support BV staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden e-mail, noch voor een tijdige ontvangst daarvan.


________________________________
Van: René Terstegen <notifications@github.com>
Verzonden: vrijdag 30 augustus 2019 13:56
Aan: MartijnLans/PM-TOP <PM-TOP@noreply.github.com>
CC: Martijn Lans <martijn.lans@onderwijssupport.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [MartijnLans/PM-TOP] 500 Internal Server Error (#35)


Ik vrees dat het probleem echt te maken heeft met de hosting. Heb je voor mij de gegevens waarme ik kan contacten met de systeembeheerder van het hostingplatform? Dan kan ik het even direct met hem opnemen.

Aan de code ligt het iig niet, want het werkt op mijn omgeving helemaal prima.

**Comment by MartijnLans** [comment]
Zojuist getest, probleem is opgelost voor zover ik kan zien.
