### ISSUE TITLE
Rooster wisseling, WTF

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#4]
In de overeenkomst op het tabblad "Werktijdfactor" wordt de WTF soms verkeerd berekend.

Als werkdagen uit gevinkt worden, en er daarna van rooster gewisseld wordt, dan wordt de WTF berekend alsof deze dagen wel aangevinkt staan.

Als deze dagen vervolgens aangezet worden en weer uit, dan wordt de WTF weer juist berekend.

**Comment by stegeman** [comment]
Fix voor dit issue staat op test. Check even of het werkt, dan kan het naar productie.

**Comment by MartijnLans** [comment]
Hoi René,

Het rooster wisselen werkt zoals het zou moeten, echter zijn de volgende fouten ontstaan met deze fix:
Ik heb een oud aangemaakte overeenkomst gebruikt om te testen. 
- de maandag stond uit gevinkt, als ik deze aan vink dan komen er geen uren te staan (ook niet na opslaan). Als ik het rooster vervang (op kies zetten, daarna hetzelfde rooster weer selecteren)  dan komen de uren er wel correct in te staan.
- visuele bug, als een dag uit gevinkt wordt dan blijven de niet lesgebonden uren van die dag staan. Deze worden niet meegerekend en worden bij het opslaan ook weg gehaald. Hetzelfde geldt voor de uren in de kolom "Uren p/dag".

Misschien handig om bij dit probleem ook het 2e deel van https://github.com/MartijnLans/PM-TOP/issues/12 mee te nemen. Ik weet het natuurlijk niet, maar het lijkt mij dat dit in hetzelfde stuk code zit :)

**Comment by stegeman** [comment]
Ha Martijn,

Op test heb ik een nieuwe oplossing voor dit probleem geplaatst. Hiervoor heb ik het hele javascript gedeelte herschreven, dus check goed of alle functionaliteit nog doet wat het moet doen.

**Comment by MartijnLans** [comment]
Hoi René,

Allereerst: fijn dat er eerst een rooster gekozen moet worden, ziet er goed uit.

De volgende issues ben ik tegengekomen tijdens het testen:
- Twee-wekelijks rooster aanvinken en invullen, daarna opslaan verbergt het 2e rooster. Als je naar een ander tabblad gaat en weer terug naar tabblad werktijdfactor blijft deze verborgen.
- Als een dag inactief staat, en daarna actief gemaakt wordt, dan worden de totaal uren niet ge-update. Bij het inactief maken van dagen werkt dit wel. Dit gebeurt alleen nadat de inactieve dagen zijn opgeslagen.

**Comment by stegeman** [comment]
Beide bovenstaande punten zijn opgelost. Staan op acceptatie

**Comment by MartijnLans** [comment]
Dit werk prima en kan naar de live versie doorgezet worden.

**Comment by stegeman** [comment]
Vandaag ga ik voor een weekje op vakantie. Om te voorkomen dat er toch iets stuk gaat bij het live zetten en ik dan op vakantie ben zal ik het begin volgende week online zetten.

**Comment by MartijnLans** [comment]
Bedankt voor het mee denken!
Ik ben echter na volgende week voorlopig even niet aan het werk.

Is het mogelijk om aan het begin van het nieuwe jaar dit online te zetten?

**Comment by stegeman** [comment]
Is helemaal prima, zet ik het in januari live.

Genier van je vrije dagen.

**Comment by MartijnLans** [comment]
Bedankt en van hetzelfde!

**Comment by stegeman** [comment]
Ha Martijn,

Komt het uit als ik komende vrijdag deze fix live zet? 

Op dit moment ben ik bezig de javascript van de application tab aan te passen. Dit is stiekem vrij complex, maar zodra ik daar een update over heb laat ik het je weten.
