### ISSUE TITLE
Overgangsrecht ouderen >57 jaar

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#5]
Als er gebruik wordt gemaakt van het overgangsrecht ouderen ouder dan 57 jaar, dan worden in de kolom "Correctie" de uren verkeerd berekend na het opslaan. De uren in kolom "Uw correctie" kloppen wel.

Als er nog niet opgeslagen is, dan klopt deze kolom wel. Issue ontstaat dus echt bij het opslaan.

**Comment by stegeman** [comment]
Dit zou nu opgelost moeten zijn. Test dit nog even goed, het staat op zowel acceptatie als productie.

**Comment by MartijnLans** [comment]
Dit lijkt nu goed te werken, mocht er nog eenzelfde fout zich voordoen dan heropen ik de issue met comment waar het precies mis gaat.
