### ISSUE TITLE
[testomgeving] Categorieën verwijderen

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#7]
Categorieën verwijderen werkt niet.

Bij de instellingen kunnen "Categorieën" aangemaakt worden. Naast de aangemaakte categorieën staat de knop "Acties" met de opties bewerk en verwijder.
De knop Verwijder geeft een pop-up "weet u zeker dat u wilt verwijderen" maar doet niks als daar op OK gedrukt wordt.

**Comment by stegeman** [comment]
Fixed!

**Comment by MartijnLans** [comment]
Op de test versie werkt dit nog niet.

**Comment by stegeman** [comment]
Aanpassing in template is nu ook op acceptatie gezet

**Comment by MartijnLans** [comment]
Op de test omgeving geeft dit een 403 error. Zolang dit op Live blijft werken vind ik het even prima.
