### ISSUE TITLE
Duurzame inzetbaarheidsuren sparen

### ISSUE THREAD

**Issue by MartijnLans** [MartijnLans/PM-TOP#8]
Als een medewerker zijn duurzame uren wilt sparen, dan kan dit worden ingevuld bij de regeling duurzame inzetbaarheidsuren en overig verlof. Voor het voorbeeld is er gebruikt gemaakt van WTF 1,0. Hierbij is de lesgevende taak 930, opslagfactor 35% (326 uur), prof. 83, overige taken 280 en duurzaamheid 40.
Op het moment gebeurt het volgende:

(1) sparen duurzame inzetbaarheid - Ja
-40 duurzame inzetbaarheidsuren
+40 overige taken
Dit is juist.

(4) recht op bijzonder budget ouderen - Ja
-75 Lesgevende taak
-26 opslagfactor
-29 overige taken
+130 duurzame uren
Dit is juist

(5) spaart u het bijzonder budget ouderen (in combinatie met (4)) - Ja
geen correcties meer, PM-TOP laat 0 zien bij uw correctie.
Hier zouden dezelfde waarden moeten staan als bij 4, maar dan op de volgende manier:
-75 lesgevende taak
-26 opslagfactor
-29 + 130 overige taken = + 101
+130 - 130 duurzaame uren = 0

Het sparen van het bijzonder budget ouderen werkt hierdoor niet.

**Comment by stegeman** [comment]
De gecorrigeerde code staat op test. Kan getest worden.

**Comment by MartijnLans** [comment]
Het gaat bijna goed. De losse opties werken nu prima.
Echter als 1, 4 en 5 tegelijk gebruikt worden, dan wordt er verkeerd gecorrigeerd op de lesgevende taak.

Als ik reken met dezelfde uren als die hier boven staan, dan zie ik het volgende als 4+5 gebruikt worden:
-75 lesgevende taak
-26 opslagfactor
0 professionalisering
+101 overige taken
Dit is juist.

Als ik dan optie 1 aanzet, veranderen de uren voor de lesgevende taak. Deze worden bij los gebruik van optie 1 niet gecorrigeerd (zoals het hoort). Het wordt dan:
**-73** (moet zijn -75)
-26
0
**+139** (moet zijn -141)

**Comment by stegeman** [comment]
> Als ik dan optie 1 aanzet, veranderen de uren voor de lesgevende taak. Deze worden bij los gebruik van optie 1 niet gecorrigeerd (zoals het hoort). Het wordt dan:
-73 (moet zijn -75)
-26
0
+139 (moet zijn -141)

Moet die -141 daadwerkelijk negatief zijn? Lijkt me dat dat dan +141 moet zijn. Anders snap ik de berekening niet meer vrees ik :).

**Comment by MartijnLans** [comment]
Sorry, inderdaad +141.

**Comment by stegeman** [comment]
Fix staat op acceptatie. Hoor graag of het nu wel helemaal werkt zoals bedoeld.

**Comment by MartijnLans** [comment]
Na het testen lijkt dit nog niet helemaal juist te werken.
Alle 3 de opties aan levert nu het juiste resultaat.

Als ik echter optie 1 en 4 tegelijk gebruik, heeft dat alsnog op een of andere manier invloed op de lesgevende taak (-73 ipv -75). Hierdoor ontstaat er onderaan een verschil van 2 uur. Volgens mij werkt het verder goed.

**Comment by stegeman** [comment]
Fixed again :)

**Comment by MartijnLans** [comment]
Ik kan hier geen fouten meer in vinden, bedankt! Dit kan naar live.
Mocht ik toch nog iets tegenkomen, dan heropen ik de issue.
